# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Messaging'

target 'vanchuyen24' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for vanchuyen24

#  target 'vanchuyen24-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

  #target 'vanchuyen24Tests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end

#target 'vanchuyen24-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vanchuyen24-tvOS

#  target 'vanchuyen24-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#end
